FROM node:18-alpine
WORKDIR /app

RUN apk update && apk add --no-cache openssl

# Copy early on to prevent reinstalling dependencies when code (and not dependency config) changes
COPY ./package*.json ./
COPY ./tsconfig*.json ./

RUN npm ci

# Copy entire project, including source code
COPY ./ ./

# Run script to generate model files, and pre-dev requirements
RUN npm run db:generate
RUN npm run pre:dev

CMD ["npm", "start"]