import { getEmployeeApproversWithDefaults } from '../employee-approver.service';

jest.mock('../../repositories/company-approver.repository');
jest.mock('../../repositories/company-level.repository');
jest.mock('../../repositories/company-tree-node.repository');
jest.mock('../../repositories/department-leadership.repository');
jest.mock('../../repositories/employee-approver.repository');
jest.mock('../../repositories/employee.repository');
jest.mock('../../repositories/grade-level');

describe(('unit test for GetEmployeeApproversWithDefaults'), () => {
  it(('Gets approvers for employee with employee approver at levels 1 and 2'), async () => {
    await expect(getEmployeeApproversWithDefaults({
      employeeId: 1,
      approvalType: 'leave',
    })).resolves.toStrictEqual([
      {
        approverId: 2, 
        createdAt: '2024-09-27T15:11:18.372Z', 
        employeeId: 1, 
        id: 1, 
        level: 1, 
        modifiedAt: '2024-09-27T15:11:18.372Z',
      }, 
      {
        approverId: 8, 
        createdAt: '2024-09-27T15:11:18.372Z', 
        employeeId: 1, 
        id: 3, 
        level: 2, 
        modifiedAt: '2024-09-27T15:11:18.372Z'
      }
    ]);
  });

  it(('Gets approvers for employee with employee approver at only level 1'), async () => {
    await expect(getEmployeeApproversWithDefaults({
      employeeId: 3,
      approvalType: 'leave',
    })).resolves.toStrictEqual([
      {
        'approverId': 2,
        'createdAt': '2024-09-27T15:11:18.372Z',
        'employeeId': 3,
        'id': 2,
        'level': 1,
        'modifiedAt': '2024-09-27T15:11:18.372Z',
      },
      {
        'approver':  {
          'address': null,
          'alternateMsisdn': '',
          'company':  {
            'address': 'zo2j34',
            'allowNegativeRates': false,
            'allowNegativeRatesLastModifiedAt': '2024-07-22T00:00:00.000Z',
            'considerPublicHolidayAsWorkday': false,
            'considerWeekendAsWorkday': false,
            'contactEmail': 'conatact@gmail.com',
            'contactMsisdn': null,
            'countryId': null,
            'createdAt': new Date('2024-07-03'),
            'currencyId': 1,
            'enableEmployeeLogin': true,
            'id': 2,
            'leaveRequestApprovalsRequired': 2,
            'logoUrl': null,
            'modifiedAt': new Date('2024-07-22'),
            'name': 'test company',
            'notifyApproversOnRequestResponse': false,
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
            'reimbursementRequestApprovalsRequired': 1,
            'status': 'ACTIVE',
            'statusLastModifiedAt': new Date('2024-07-22'),
            'workHoursInADay': 8,
          },
          'companyId': 2,
          'costAreaId': null,
          'createdAt': new Date('2024-11-20'),
          'dateOfBirth': null,
          'departmentId': null,
          'digitalAddress': null,
          'divisionId': null,
          'email': 'achanamoseyj@gmail.com',
          'employeeNumber': 'EMP00005',
          'employmentDate': new Date('2017-09-27'),
          'excludeFromPayrollRun': false,
          'firstName': 'Sarah',
          'gender': 'FEMALE',
          'hr': false,
          'id': 5,
          'jobTitleId': null,
          'lastName': 'Connor',
          'majorGradeLevel':  {
            'code': 'GMJ01',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'id': 4,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'test',
            'type': 'MAJOR',
          },
          'majorGradeLevelId': 2,
          'minorGradeLevelId': 1,
          'modifiedAt': new Date('2024-11-20'),
          'msisdn': '233547022937',
          'nationality': 'English',
          'notchId': 1,
          'otherNames': null,
          'pensioner': false,
          'photoUrl': null,
          'privateEmail': null,
          'reemployed': false,
          'regionId': null,
          'resident': true,
          'ssn': '3232323',
          'stationId': null,
          'status': 'ACTIVE',
          'statusLastModifiedAt': null,
          'taxIdentificationNumber': '24223235555',
          'terminationDate': null,
          'title': 'Mrs.',
          'tribeId': null,
          'unionMember': false,
          'userId': null,
          'username': '',
        },
        'approverId': 5,
        'employee':  {
          'address': null,
          'alternateMsisdn': '',
          'company':  {
            'address': 'zo2j34',
            'allowNegativeRates': false,
            'allowNegativeRatesLastModifiedAt': '2024-07-22T00:00:00.000Z',
            'considerPublicHolidayAsWorkday': false,
            'considerWeekendAsWorkday': false,
            'contactEmail': 'conatact@gmail.com',
            'contactMsisdn': null,
            'countryId': null,
            'createdAt': new Date('2024-07-03'),
            'currencyId': 1,
            'enableEmployeeLogin': true,
            'id': 1,
            'leaveRequestApprovalsRequired': 2,
            'logoUrl': null,
            'modifiedAt': new Date('2024-07-22'),
            'name': 'test company',
            'notifyApproversOnRequestResponse': false,
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
            'reimbursementRequestApprovalsRequired': 1,
            'status': 'ACTIVE',
            'statusLastModifiedAt': new Date('2024-07-22'),
            'workHoursInADay': 8,
          },
          'companyId': 1,
          'costAreaId': null,
          'createdAt': new Date('2024-11-20'),
          'dateOfBirth': new Date('1940-01-02'),
          'departmentId': null,
          'digitalAddress': null,
          'divisionId': null,
          'email': 'achanamoseyj@gmail.com',
          'employeeNumber': 'EMP00003',
          'employmentDate': new Date('2017-09-27'),
          'excludeFromPayrollRun': false,
          'firstName': 'Sarah',
          'gender': 'FEMALE',
          'hr': false,
          'id': 3,
          'jobTitle':  {
            'acceptDisability': true,
            'code': 'JB001',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'employeeBandId': 1,
            'id': 1,
            'maximumAge': null,
            'minimumAge': null,
            'minimumExperienceYears': null,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'Manager nk',
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
          },
          'jobTitleId': 1,
          'lastName': 'Connor',
          'majorGradeLevel':  {
            'code': 'GMJ01',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'id': 4,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'test',
            'type': 'MAJOR',
          },
          'majorGradeLevelId': 4,
          'minorGradeLevelId': 1,
          'modifiedAt': new Date('2024-11-20'),
          'msisdn': '233547022937',
          'nationality': 'English',
          'notchId': 1,
          'otherNames': null,
          'pensioner': false,
          'photoUrl': null,
          'privateEmail': null,
          'reemployed': false,
          'regionId': null,
          'resident': true,
          'ssn': '',
          'stationId': null,
          'status': 'ACTIVE',
          'statusLastModifiedAt': null,
          'taxIdentificationNumber': '24223235555',
          'terminationDate': null,
          'title': 'Mrs.',
          'tribeId': null,
          'unionMember': false,
          'userId': null,
          'username': 'achanamoseyj@gmail.com',
        },
        'employeeId': 3,
        'level': 2,
      },
      {
        'approver':  {
          'address': null,
          'alternateMsisdn': '',
          'company':  {
            'address': 'zo2j34',
            'allowNegativeRates': false,
            'allowNegativeRatesLastModifiedAt': new Date('2024-07-22T00:00:00.000Z'),
            'considerPublicHolidayAsWorkday': false,
            'considerWeekendAsWorkday': false,
            'contactEmail': 'conatact@gmail.com',
            'contactMsisdn': null,
            'countryId': null,
            'createdAt': new Date('2024-07-03'),
            'currencyId': 1,
            'enableEmployeeLogin': true,
            'id': 2,
            'leaveRequestApprovalsRequired': 2,
            'logoUrl': null,
            'modifiedAt': new Date('2024-07-22'),
            'name': 'test company',
            'notifyApproversOnRequestResponse': false,
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
            'reimbursementRequestApprovalsRequired': 1,
            'status': 'ACTIVE',
            'statusLastModifiedAt': new Date('2024-07-22'),
            'workHoursInADay': 8,
          },
          'companyId': 2,
          'costAreaId': null,
          'createdAt': new Date('2024-11-20'),
          'dateOfBirth': null,
          'departmentId': null,
          'digitalAddress': null,
          'divisionId': null,
          'email': 'achanamoseyj@gmail.com',
          'employeeNumber': 'EMP00006',
          'employmentDate': new Date('2017-09-27'),
          'excludeFromPayrollRun': false,
          'firstName': 'Sarah',
          'gender': 'FEMALE',
          'hr': false,
          'id': 6,
          'jobTitleId': null,
          'lastName': 'Connor',
          'majorGradeLevel':  {
            'code': 'GMJ01',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'id': 4,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'test',
            'type': 'MAJOR',
          },
          'majorGradeLevelId': 3,
          'minorGradeLevelId': 1,
          'modifiedAt': new Date('2024-11-20'),
          'msisdn': '233547022937',
          'nationality': 'English',
          'notchId': 1,
          'otherNames': null,
          'pensioner': false,
          'photoUrl': null,
          'privateEmail': null,
          'reemployed': false,
          'regionId': null,
          'resident': true,
          'ssn': '3232323',
          'stationId': null,
          'status': 'ACTIVE',
          'statusLastModifiedAt': null,
          'taxIdentificationNumber': '24223235555',
          'terminationDate': null,
          'title': 'Mrs.',
          'tribeId': null,
          'unionMember': false,
          'userId': null,
          'username': '',
        },
        'approverId': 6,
        'employee':  {
          'address': null,
          'alternateMsisdn': '',
          'company':  {
            'address': 'zo2j34',
            'allowNegativeRates': false,
            'allowNegativeRatesLastModifiedAt': new Date('2024-07-22T00:00:00.000Z'),
            'considerPublicHolidayAsWorkday': false,
            'considerWeekendAsWorkday': false,
            'contactEmail': 'conatact@gmail.com',
            'contactMsisdn': null,
            'countryId': null,
            'createdAt': new Date('2024-07-03'),
            'currencyId': 1,
            'enableEmployeeLogin': true,
            'id': 1,
            'leaveRequestApprovalsRequired': 2,
            'logoUrl': null,
            'modifiedAt': new Date('2024-07-22'),
            'name': 'test company',
            'notifyApproversOnRequestResponse': false,
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
            'reimbursementRequestApprovalsRequired': 1,
            'status': 'ACTIVE',
            'statusLastModifiedAt': new Date('2024-07-22'),
            'workHoursInADay': 8,
          },
          'companyId': 1,
          'costAreaId': null,
          'createdAt': new Date('2024-11-20'),
          'dateOfBirth': new Date('1940-01-02'),
          'departmentId': null,
          'digitalAddress': null,
          'divisionId': null,
          'email': 'achanamoseyj@gmail.com',
          'employeeNumber': 'EMP00003',
          'employmentDate': new Date('2017-09-27'),
          'excludeFromPayrollRun': false,
          'firstName': 'Sarah',
          'gender': 'FEMALE',
          'hr': false,
          'id': 3,
          'jobTitle':  {
            'acceptDisability': true,
            'code': 'JB001',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'employeeBandId': 1,
            'id': 1,
            'maximumAge': null,
            'minimumAge': null,
            'minimumExperienceYears': null,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'Manager nk',
            'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
          },
          'jobTitleId': 1,
          'lastName': 'Connor',
          'majorGradeLevel':  {
            'code': 'GMJ01',
            'companyId': 1,
            'companyLevelId': 1,
            'createdAt': new Date('2024-11-20'),
            'description': '',
            'id': 4,
            'modifiedAt': new Date('2024-11-20'),
            'name': 'test',
            'type': 'MAJOR',
          },
          'majorGradeLevelId': 4,
          'minorGradeLevelId': 1,
          'modifiedAt': new Date('2024-11-20'),
          'msisdn': '233547022937',
          'nationality': 'English',
          'notchId': 1,
          'otherNames': null,
          'pensioner': false,
          'photoUrl': null,
          'privateEmail': null,
          'reemployed': false,
          'regionId': null,
          'resident': true,
          'ssn': '',
          'stationId': null,
          'status': 'ACTIVE',
          'statusLastModifiedAt': null,
          'taxIdentificationNumber': '24223235555',
          'terminationDate': null,
          'title': 'Mrs.',
          'tribeId': null,
          'unionMember': false,
          'userId': null,
          'username': 'achanamoseyj@gmail.com',
        },
        'employeeId': 3,
        'level': 2,
      },
    ]);
  });
});