import {  Prisma } from '@prisma/client';
import { EmployeeDto } from '../../domain/events/employee.event';
import { getListWithPagination, ListWithPagination } from '../types';

const dataStore: EmployeeDto[] = [
  {
    'id': 1,
    'companyId': 1,
    'notchId': 1,
    'employeeNumber': 'EMP00001',
    'title': 'test',
    'firstName': 'dd',
    'lastName': 'kdsfj',
    'otherNames': null,
    'gender': 'MALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '',
    'taxIdentificationNumber': null,
    'majorGradeLevelId': null,
    'minorGradeLevelId': null,
    'nationality': 'Ghanaian',
    'regionId': null,
    'tribeId': null,
    'email': '',
    'privateEmail': null,
    'msisdn': null,
    'alternateMsisdn': null,
    'address': null,
    'digitalAddress': null,
    'jobTitleId': 1,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': false,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'jobTitle': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'companyId': 1,
      'employeeBandId': 1,
      'code': 'JB001',
      'description': '',
      'name': 'Manager nk',
      'companyLevelId': 1,
      'minimumAge': null,
      'maximumAge': null,
      'minimumExperienceYears': null,
      'acceptDisability': true,
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
    'majorGradeLevel': undefined,
  },
  {
    'id': 2,
    'companyId': 1,
    'notchId': 1,
    'employeeNumber': 'EMP00002',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': 1,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': 'achanamoseyj@gmail.com',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'jobTitle': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'companyId': 1,
      'employeeBandId': 1,
      'code': 'JB001',
      'description': '',
      'name': 'Manager nk',
      'companyLevelId': 1,
      'minimumAge': null,
      'maximumAge': null,
      'minimumExperienceYears': null,
      'acceptDisability': true,
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    }
  },
  {
    'id': 3,
    'companyId': 1,
    'notchId': 1,
    'employeeNumber': 'EMP00003',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': 1,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': 'achanamoseyj@gmail.com',
    'statusLastModifiedAt': null,
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'jobTitle': {
      'id': 1,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'companyId': 1,
      'employeeBandId': 1,
      'code': 'JB001',
      'description': '',
      'name': 'Manager nk',
      'companyLevelId': 1,
      'minimumAge': null,
      'maximumAge': null,
      'minimumExperienceYears': null,
      'acceptDisability': true,
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 4,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00004',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 5,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00005',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 2,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 6,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00006',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 3,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 7,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00007',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 8,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00008',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 9,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00009',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
  {
    'id': 10,
    'companyId': 2,
    'notchId': 1,
    'employeeNumber': 'EMP00010',
    'title': 'Mrs.',
    'firstName': 'Sarah',
    'lastName': 'Connor',
    'otherNames': null,
    'gender': 'FEMALE',
    'dateOfBirth': new Date('1940-01-02'),
    'photoUrl': null,
    'ssn': '3232323',
    'taxIdentificationNumber': '24223235555',
    'majorGradeLevelId': 4,
    'minorGradeLevelId': 1,
    'nationality': 'English',
    'regionId': null,
    'tribeId': null,
    'email': 'achanamoseyj@gmail.com',
    'privateEmail': null,
    'msisdn': '233547022937',
    'alternateMsisdn': '',
    'address': null,
    'digitalAddress': null,
    'jobTitleId': null,
    'departmentId': null,
    'divisionId': null,
    'stationId': null,
    'costAreaId': null,
    'status': 'ACTIVE',
    'employmentDate': new Date('2017-09-27'),
    'terminationDate': null,
    'reemployed': false,
    'resident': true,
    'unionMember': false,
    'hr': false,
    'username': '',
    'pensioner': false,
    'userId': null,
    'excludeFromPayrollRun': false,
    'maritalStatus': null,
    'statusLastModifiedAt': null,
    'createdAt': new Date('2024-11-20'),
    'modifiedAt': new Date('2024-11-20'),
    'company': {
      'id': 2,
      'organizationId': '39f2a042-747d-4200-9bdd-cac11538249a',
      'name': 'test company',
      'address': 'zo2j34',
      'logoUrl': null,
      'contactEmail': 'conatact@gmail.com',
      'contactMsisdn': null,
      'status': 'ACTIVE',
      'currencyId': 1,
      'countryId': null,
      'allowNegativeRates': false,
      'considerPublicHolidayAsWorkday': false,
      'considerWeekendAsWorkday': false,
      'enableEmployeeLogin': true,
      'workHoursInADay': 8,
      'leaveRequestApprovalsRequired': 2,
      'reimbursementRequestApprovalsRequired': 1,
      'notifyApproversOnRequestResponse': false,
      'notifyHrOnLeaveRequest': false,
      'notifyHrOnReimbursementRequest': false, 
      'createdAt': new Date('2024-07-03'),
      'modifiedAt': new Date('2024-07-22'),
      'statusLastModifiedAt': new Date('2024-07-22'),
      'allowNegativeRatesLastModifiedAt': new Date('2024-07-22')
    },
    'majorGradeLevel': {
      'id': 4,
      'companyId': 1,
      'companyLevelId': 1,
      'name': 'test',
      'code': 'GMJ01',
      'description': '',
      'type': 'MAJOR',
      'createdAt': new Date('2024-11-20'),
      'modifiedAt': new Date('2024-11-20'),
    },
  },
];

type inObject = {
  in: number[];
}

export const findOne = jest.fn().mockImplementation(
  async (
    whereUniqueInput: Prisma.EmployeeWhereUniqueInput
  ): Promise<EmployeeDto | null> => {
    let result: EmployeeDto | undefined;
    
    if (whereUniqueInput.id) {
      result = dataStore.find(item => {
        return item.id === whereUniqueInput.id;
      });
    }
    
    return result ?? null;
  }
);

export const findFirst = jest.fn().mockImplementation(
  async (
    whereInput: Prisma.EmployeeWhereInput,
  ): Promise<EmployeeDto | null> => {
    let result: EmployeeDto | undefined;
    if (whereInput.companyId) {
      result = dataStore.find(item => {
        return item.companyId === whereInput.companyId 
          && item.employeeNumber === whereInput.employeeNumber;
      });
    } else if (whereInput.majorGradeLevelId && typeof whereInput === 'object') {
      const where = whereInput.majorGradeLevelId as unknown as inObject;
      result = dataStore.find(item => {
        if(item.majorGradeLevelId) {
          return where.in.includes(item.majorGradeLevelId);
        }
      });
    }  
    
  
    return result ?? null;
  }
);


export const count = jest.fn().mockImplementation(
  async (
    whereInput: Prisma.EmployeeWhereInput,
  ): Promise<number> => {
    let count = 0;
    if (whereInput.company) {
      dataStore.forEach(item => {
        if (whereInput.company?.organizationId === item.company?.organizationId) {
          count++;
        }
      });
    }

    return count;
  });


export const find = jest.fn().mockImplementation(
  async (params: {
    skip?: number,
    take?: number,
    where?: Prisma.EmployeeWhereInput,
    orderBy?: Prisma.EmployeeOrderByWithRelationAndSearchRelevanceInput,
    include?: Prisma.EmployeeInclude
  }): Promise<ListWithPagination<EmployeeDto>> => {
    let result: EmployeeDto[] = 
    JSON.parse(JSON.stringify(dataStore)) as typeof dataStore;

    const { skip, take } = params;
    const paginate = skip !== undefined && take !== undefined;
    if (params.where?.majorGradeLevelId !== undefined) {
      if (typeof params.where.majorGradeLevelId === 'object') {
        const param = params.where.majorGradeLevelId as unknown as inObject;
        result = result.filter((item) => {
          if (item.majorGradeLevelId && param.in.includes(item.majorGradeLevelId)) {
            return true;
          }
        });
      }else {
        result = result.filter(
          (item) => item.majorGradeLevelId === params.where?.majorGradeLevelId
        );
      }
      
    } 
    
    if (params.where?.id !== undefined) {
      result = result.filter(
        (item) => item?.id === params.where?.id
      );
    }
    result = result.slice(params.skip);
    result = result.slice(0, params.take);

    const totalCount = paginate ? result.length : undefined;
    return getListWithPagination(result, { skip, take, totalCount });
  }
);
